imports:
    - 'package-container.yml'
    - 'vendor/opine/route/config/package-container.yml'
    - 'vendor/opine/collection/config/package-container.yml'
    - 'vendor/opine/language/config/package-container.yml'
    - 'vendor/opine/build/config/package-container.yml'
    - 'vendor/opine/config/config/package-container.yml'
    - 'vendor/opine/helper/config/package-container.yml'
    - 'vendor/opine/bundle/config/package-container.yml'
    - 'vendor/opine/field/config/package-container.yml'
    - 'vendor/opine/container/config/package-container.yml'
    - 'vendor/opine/layout/config/package-container.yml'
    - 'vendor/opine/handlebars/config/package-container.yml'
    - 'vendor/opine/db/config/package-container.yml'
    - 'vendor/opine/http/config/package-container.yml'
    - 'vendor/opine/person/config/package-container.yml'
    - 'vendor/opine/queue/config/package-container.yml'
    - 'vendor/opine/search/config/package-container.yml'
    - 'vendor/opine/mail/config/package-container.yml'
    - 'vendor/opine/uploadwrapper/config/package-container.yml'
    - 'vendor/opine/imageresizer/config/package-container.yml'

services:
    test:
        class:     'Opine\Form\TestService'
        arguments: ['@post']